version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: workplace_vibe_backend
    ports:
      - 8000:8000
    volumes:
      - ./backend:/app
      - ./backend/workplace_vibe.db:/app/workplace_vibe.db
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - PYTHONBUFFERED=1
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]

volumes:
  workplace_vibe_db:
    driver: local


